import type { Restaurant, OpeningHours } from "./types";

// Common opening-hour presets
const allDay: OpeningHours[] = Array.from({ length: 7 }, (_, day) => ({
  day,
  open: "00:00",
  close: "23:59",
}));
const standard: OpeningHours[] = Array.from({ length: 7 }, (_, day) => ({
  day,
  open: "10:00",
  close: "23:00",
}));
const cafe: OpeningHours[] = Array.from({ length: 7 }, (_, day) => ({
  day,
  open: "07:00",
  close: "22:00",
}));
const evening: OpeningHours[] = Array.from({ length: 7 }, (_, day) => ({
  day,
  open: "17:00",
  close: "23:30",
}));

const p = (id: string) => `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=1000`;

/**
 * Local seed data. Acts as an offline-friendly fallback whenever Firestore is
 * empty or unreachable, so the site always renders something meaningful.
 */
export const seedRestaurants: Restaurant[] = [
  {
    id: "dinemore",
    slug: "dinemore",
    name: "Dinemore",
    cuisine: ["Seafood", "Grill"],
    priceLevel: 2,
    rating: 4.5,
    reviewCount: 218,
    description:
      "A breezy beachfront spot serving the day's freshest catch with an unbeatable ocean view. Come for the grilled reef fish, stay for the sunset.",
    image: p("1435904"),
    gallery: [p("1435904"), p("262978"), p("725991"), p("1058277")],
    location: "Malé",
    address: "Boduthakurufaanu Magu, Malé",
    coords: { lat: 4.1755, lng: 73.5093 },
    tags: ["Ocean View", "24/7", "Fresh Seafood", "Date Spots"],
    phone: "+960 330 1234",
    email: "hello@dinemore.mv",
    hours: allDay,
    featured: true,
    createdAt: 1710000000000,
  },
  {
    id: "chicking",
    slug: "chicking",
    name: "Chicking",
    cuisine: ["Fast Food", "Fried Chicken"],
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 512,
    description:
      "Crispy, juicy fried chicken and loaded burgers. A reliable go-to for a quick, hearty bite any time of day.",
    image: p("2338407"),
    gallery: [p("2338407"), p("60616"), p("1600711")],
    location: "Hulhumalé",
    address: "Nirolhu Magu, Hulhumalé",
    coords: { lat: 4.2105, lng: 73.5406 },
    tags: ["Fast food", "Family", "Takeaway", "Budget"],
    phone: "+960 333 2211",
    email: "order@chicking.mv",
    hours: standard,
    createdAt: 1712000000000,
  },
  {
    id: "marrybrown",
    slug: "marrybrown",
    name: "MarryBrown",
    cuisine: ["Fusion", "International"],
    priceLevel: 3,
    rating: 4.7,
    reviewCount: 341,
    description:
      "A chic downtown table plating a confident fusion of international cuisines in a sleek, modern room.",
    image: p("941861"),
    gallery: [p("941861"), p("1279330"), p("1633578")],
    location: "Malé",
    address: "Majeedhee Magu, Malé",
    coords: { lat: 4.1748, lng: 73.5089 },
    tags: ["Modern", "Fusion Cuisine", "Chic", "Date Spots"],
    phone: "+960 332 5566",
    email: "reserve@marrybrown.mv",
    hours: standard,
    featured: true,
    createdAt: 1709000000000,
  },
  {
    id: "grillhut",
    slug: "grillhut",
    name: "GrillHut",
    cuisine: ["Grill", "Steakhouse"],
    priceLevel: 3,
    rating: 4.9,
    reviewCount: 176,
    description:
      "Farm-to-table grilling with an obsession for organic, locally-sourced ingredients and perfectly charred cuts.",
    image: p("1105325"),
    gallery: [p("1105325"), p("299347"), p("618775")],
    location: "Hulhumalé",
    address: "Central Park, Hulhumalé",
    coords: { lat: 4.2119, lng: 73.5411 },
    tags: ["Organic", "Farm-to-Table", "Date Spots", "Top rated"],
    phone: "+960 335 7788",
    email: "grill@grillhut.mv",
    hours: evening,
    featured: true,
    createdAt: 1707000000000,
  },
  {
    id: "bakerloo",
    slug: "bakerloo",
    name: "Bakerloo",
    cuisine: ["Café", "Bakery"],
    priceLevel: 2,
    rating: 4.6,
    reviewCount: 287,
    description:
      "An artisan bakery and café pulling shots of specialty coffee beside flaky pastries baked fresh every morning.",
    image: p("302899"),
    gallery: [p("302899"), p("205961"), p("1055272")],
    location: "Malé",
    address: "Chaandhanee Magu, Malé",
    coords: { lat: 4.1739, lng: 73.5102 },
    tags: ["Cozy", "Coffee", "Breakfast", "Cafés"],
    phone: "+960 331 4400",
    email: "hi@bakerloo.mv",
    hours: cafe,
    createdAt: 1713000000000,
  },
  {
    id: "seasalt",
    slug: "seasalt",
    name: "Sea Salt",
    cuisine: ["Seafood", "Mediterranean"],
    priceLevel: 3,
    rating: 4.8,
    reviewCount: 199,
    description:
      "Mediterranean-inspired seafood, mezze platters and citrus-bright plates served steps from the water.",
    image: p("1279330"),
    gallery: [p("1279330"), p("958545"), p("70497")],
    location: "Malé",
    address: "Rah Dhebai Hingun, Malé",
    coords: { lat: 4.1767, lng: 73.5081 },
    tags: ["Ocean View", "Date Spots", "Top rated", "Mediterranean"],
    phone: "+960 330 9090",
    email: "table@seasalt.mv",
    hours: evening,
    featured: true,
    createdAt: 1706000000000,
  },
  {
    id: "spicebazaar",
    slug: "spice-bazaar",
    name: "Spice Bazaar",
    cuisine: ["Indian", "Curry"],
    priceLevel: 2,
    rating: 4.4,
    reviewCount: 263,
    description:
      "Fragrant biryanis, tandoori grills and rich curries cooked low and slow with hand-ground spices.",
    image: p("1640777"),
    gallery: [p("1640777"), p("2474661"), p("1624487")],
    location: "Hulhumalé",
    address: "Beach Road, Hulhumalé",
    coords: { lat: 4.2098, lng: 73.5423 },
    tags: ["Spicy", "Family", "Vegetarian", "Halal"],
    phone: "+960 334 1212",
    email: "eat@spicebazaar.mv",
    hours: standard,
    createdAt: 1711500000000,
  },
  {
    id: "sakura",
    slug: "sakura",
    name: "Sakura",
    cuisine: ["Japanese", "Sushi"],
    priceLevel: 3,
    rating: 4.7,
    reviewCount: 154,
    description:
      "An intimate sushi counter with omakase evenings, precise nigiri and a quietly excellent sake list.",
    image: p("357756"),
    gallery: [p("357756"), p("2098085"), p("1148087")],
    location: "Malé",
    address: "Ameenee Magu, Malé",
    coords: { lat: 4.1721, lng: 73.5111 },
    tags: ["Sushi", "Date Spots", "Top rated", "Quiet"],
    phone: "+960 332 8899",
    email: "reserve@sakura.mv",
    hours: evening,
    createdAt: 1705000000000,
  },
  {
    id: "tikitaka",
    slug: "tiki-taka",
    name: "Tiki Taka",
    cuisine: ["Tapas", "Spanish"],
    priceLevel: 2,
    rating: 4.3,
    reviewCount: 132,
    description:
      "A lively tapas bar for sharing plates and sangria — patatas bravas, garlic prawns and late-night buzz.",
    image: p("941869"),
    gallery: [p("941869"), p("761854"), p("1267320")],
    location: "Hulhumalé",
    address: "Hiyaa Flats, Hulhumalé",
    coords: { lat: 4.2132, lng: 73.5399 },
    tags: ["Lively", "Sharing", "Date Spots", "Late Night"],
    phone: "+960 335 3434",
    email: "hola@tikitaka.mv",
    hours: evening,
    createdAt: 1710500000000,
  },
  {
    id: "greenleaf",
    slug: "green-leaf",
    name: "Green Leaf",
    cuisine: ["Vegan", "Healthy"],
    priceLevel: 2,
    rating: 4.5,
    reviewCount: 118,
    description:
      "Plant-forward bowls, cold-pressed juices and guilt-free desserts for the health-conscious islander.",
    image: p("1092730"),
    gallery: [p("1092730"), p("1213710"), p("1640774")],
    location: "Malé",
    address: "Sosun Magu, Malé",
    coords: { lat: 4.1758, lng: 73.5075 },
    tags: ["Vegan", "Healthy", "Cafés", "Vegetarian"],
    phone: "+960 331 7676",
    email: "hello@greenleaf.mv",
    hours: cafe,
    createdAt: 1712500000000,
  },
  {
    id: "burgerbros",
    slug: "burger-bros",
    name: "Burger Bros",
    cuisine: ["Fast Food", "Burgers"],
    priceLevel: 1,
    rating: 4.1,
    reviewCount: 402,
    description:
      "Smash burgers, crinkle fries and thick shakes. No frills, all flavour — the classic quick fix.",
    image: p("1639557"),
    gallery: [p("1639557"), p("1600727"), p("70497")],
    location: "Hulhumalé",
    address: "Bageechaa Magu, Hulhumalé",
    coords: { lat: 4.2087, lng: 73.5417 },
    tags: ["Fast food", "Budget", "Takeaway", "Family"],
    phone: "+960 333 1010",
    email: "yo@burgerbros.mv",
    hours: standard,
    createdAt: 1713500000000,
  },
  {
    id: "lagoon",
    slug: "lagoon",
    name: "Lagoon Rooftop",
    cuisine: ["International", "Cocktails"],
    priceLevel: 4,
    rating: 4.8,
    reviewCount: 96,
    description:
      "A rooftop destination for special nights — panoramic views, a global tasting menu and crafted mocktails.",
    image: p("262047"),
    gallery: [p("262047"), p("1581384"), p("34099"), p("941861")],
    location: "Malé",
    address: "Henveiru, Malé",
    coords: { lat: 4.1779, lng: 73.5064 },
    tags: ["Rooftop", "Date Spots", "Top rated", "Fine Dining"],
    phone: "+960 330 5050",
    email: "sky@lagoon.mv",
    hours: evening,
    featured: true,
    createdAt: 1704000000000,
  },
  {
    id: "islandbrew",
    slug: "island-brew",
    name: "Island Brew",
    cuisine: ["Café", "Brunch"],
    priceLevel: 2,
    rating: 4.6,
    reviewCount: 224,
    description:
      "All-day brunch, eggs done every way and a serious espresso program in a plant-filled corner café.",
    image: p("1002740"),
    gallery: [p("1002740"), p("851555"), p("312418")],
    location: "Hulhumalé",
    address: "Amin Avenue, Hulhumalé",
    coords: { lat: 4.2114, lng: 73.5388 },
    tags: ["Brunch", "Coffee", "Cafés", "Cozy"],
    phone: "+960 334 6262",
    email: "morning@islandbrew.mv",
    hours: cafe,
    createdAt: 1711000000000,
  },
  {
    id: "thaiorchid",
    slug: "thai-orchid",
    name: "Thai Orchid",
    cuisine: ["Thai", "Asian"],
    priceLevel: 2,
    rating: 4.4,
    reviewCount: 187,
    description:
      "Aromatic Thai classics — green curry, pad thai and tom yum — balanced sweet, sour, salty and hot.",
    image: p("1213710"),
    gallery: [p("1213710"), p("699953"), p("2347311")],
    location: "Malé",
    address: "Fareedhee Magu, Malé",
    coords: { lat: 4.1735, lng: 73.5097 },
    tags: ["Spicy", "Family", "Date Spots", "Asian"],
    phone: "+960 332 4747",
    email: "sawadee@thaiorchid.mv",
    hours: standard,
    createdAt: 1710800000000,
  },
];

export function getSeedRestaurants(): Restaurant[] {
  return seedRestaurants;
}
